apiVersion: apps/v1

kind: Deployment

metadata:

  name: java-deployment

  labels:

    app: java

spec:

  replicas: 1

  selector:

    matchLabels:

      app: java

  template:

    metadata:

      labels:

        app: java

    spec:

      containers:
      - name: javaapp
        image: anjanar17/argocd-java:latest
        command: ["sleep", "4800"]

        ports:

        - containerPort: 80
