apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mongodb
  namespace: mongo
spec:
  serviceName: mongo-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template: 
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo
        command:
        - mongod
        - "--bind_ip_all"
        - "--replSet"
        - rs0 
        ports:
        - containerPort: 27017
        volumeMounts: 
        - name: mongodb-data
          mountPath: /data/db
      # volumes:
      # - name: mongo-data-dir
      #   persistentVolumeClaim:
      #     claimName: ebs-claim    
  volumeClaimTemplates:
  - metadata: 
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-sc
      resources: 
        requests: 
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: mongo
spec:
  type: ClusterIP
  selector:
      app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
